//! Apple anonymous attestation (ADR-0115 §4.3a) — the Phase-0 enrolment
//! defence.
//!
//! # The hole this closes
//!
//! Phase 0 asked for `attestation: "none"` and reasoned that physical
//! presence at the Mac was the credential: only a human at the console
//! can mint an enrolment token, so whatever completes the ceremony must
//! be the operator's own device.
//!
//! That reasoning has a gap, and the gap is the relay. Until hardening
//! H1 lands, the enrolment ceremony crosses relay memory in plaintext
//! (§2.4). A compromised relay therefore sees a live, console-minted,
//! not-yet-spent enrolment token — and with `attestation: "none"` there
//! was nothing downstream that could tell the difference between a
//! passkey generated in the Secure Enclave of Ervin's iPhone and one
//! generated by fifty lines of software on the VPS. Both present a
//! public key and say "trust me". The agent trusted whichever arrived
//! first.
//!
//! An attacker who wins that race does not get a session — they get an
//! **enrolled credential**, which is standing access that survives
//! knock rotation, relay redeploys and the compromise being cleaned up.
//! That is the worst outcome in the whole threat model, and it was
//! reachable.
//!
//! So this module makes the authenticator *prove* it is Apple hardware.
//! A software-generated credential cannot produce this chain, because
//! producing it requires a key Apple's CA signed, and Apple signs only
//! keys attested by a real Secure Enclave.
//!
//! # What is verified, in order
//!
//! 1. the statement format is `apple` and carries an `x5c` chain;
//! 2. every certificate in the chain is inside its validity window;
//! 3. each certificate is signed by the next, and the last is signed by
//!    the **pinned Apple WebAuthn Root CA** (`assets/`, vendored — see
//!    that directory's README for why it is not fetched);
//! 4. the leaf carries Apple's nonce extension
//!    (`1.2.840.113635.100.8.2`) and the nonce inside it equals
//!    `SHA-256(authenticatorData ‖ clientDataHash)`;
//! 5. the leaf's public key is **the credential's own public key** —
//!    the step that binds the attestation to this credential rather
//!    than to some other credential's valid chain.
//!
//! Step 4 is what stops replay of a chain captured from a different
//! ceremony; step 5 is what stops a valid chain being pasted next to an
//! attacker's key. Both are needed, and neither is sufficient alone.
//!
//! # What this deliberately does NOT do
//!
//! No revocation check. Apple publishes no CRL or OCSP responder for
//! this hierarchy, so there is nothing to check; naming that here is
//! better than implying a check that does not exist.
//!
//! This is also **not** the end-to-end fix. §9.4's hardening H1
//! (browser↔agent inner encryption) remains Phase 2, and it is what
//! stops the relay *seeing* the ceremony at all. What this module does
//! is remove the relay's ability to turn that visibility into a
//! credential. Stated plainly so nobody reads it as more than it is.

use sha2::{Digest as _, Sha256, Sha384};
use x509_cert::der::asn1::ObjectIdentifier;
use x509_cert::der::{Decode as _, DecodePem as _, Encode as _};
use x509_cert::Certificate;

use super::cose::Es256PublicKey;

/// The pinned trust anchor. Vendored, not fetched — see
/// `assets/Apple_WebAuthn_Root_CA.README.md`.
const APPLE_ROOT_PEM: &str = include_str!("../../assets/Apple_WebAuthn_Root_CA.pem");

/// SHA-256 of the anchor's DER, asserted in the tests so a substituted
/// file fails the build rather than silently widening trust.
pub const APPLE_ROOT_SHA256: &str =
    "0915dd5c07a28db549d1f677bb5a75d4bfbe9561a773424327762e9e02f9bb29";

/// `1.2.840.113635.100.8.2` — Apple's attestation nonce extension.
const APPLE_NONCE_EXT: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.113635.100.8.2");

/// `1.2.840.10045.4.3.2` — `ecdsa-with-SHA256`.
const ECDSA_SHA256: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.10045.4.3.2");
/// `1.2.840.10045.4.3.3` — `ecdsa-with-SHA384`.
const ECDSA_SHA384: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.10045.4.3.3");

/// `1.2.840.10045.3.1.7` — NIST P-256.
const P256_CURVE: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.10045.3.1.7");
/// `1.3.132.0.34` — NIST P-384.
const P384_CURVE: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.3.132.0.34");

/// Longest attestation chain accepted. Apple sends two; the bound stops
/// a hostile statement from making the agent do unbounded signature
/// work, which is free for the sender and expensive here.
const MAX_CHAIN: usize = 4;

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum AttestationError {
    #[error(
        "attestation format is `{got}` — this deployment requires `apple` hardware attestation"
    )]
    WrongFormat { got: String },
    #[error("attestation statement carries no x5c certificate chain")]
    NoChain,
    #[error("attestation chain has {got} certificates, at most {MAX_CHAIN} are accepted")]
    ChainTooLong { got: usize },
    #[error("attestation certificate {index} is not valid DER")]
    MalformedCertificate { index: usize },
    #[error("attestation certificate {index} is outside its validity window")]
    CertificateExpired { index: usize },
    #[error("attestation chain does not lead to the Apple WebAuthn Root CA")]
    UntrustedChain,
    #[error("attestation signature at link {index} does not verify")]
    BadSignature { index: usize },
    #[error("unsupported signature algorithm {oid} in the attestation chain")]
    UnsupportedSignatureAlgorithm { oid: String },
    #[error("unsupported public key curve in the attestation chain")]
    UnsupportedCurve,
    #[error("attestation leaf carries no Apple nonce extension")]
    NoNonce,
    #[error("attestation nonce does not match this ceremony — a replayed chain")]
    NonceMismatch,
    #[error("attestation certificate does not attest THIS credential's public key")]
    KeyMismatch,
    #[error("the vendored Apple root CA is not parseable")]
    BadAnchor,
}

/// Verify one Apple anonymous attestation.
///
/// `auth_data` and `client_data_json` are the exact bytes the ceremony
/// carried — not re-serialised, because the nonce is over the bytes as
/// received and any re-encoding would change them.
///
/// `credential_key` is the public key already parsed out of
/// `auth_data`; step 5 checks the chain actually attests *it*.
pub fn verify_apple(
    fmt: &str,
    x5c: &[Vec<u8>],
    auth_data: &[u8],
    client_data_json: &[u8],
    credential_key: &Es256PublicKey,
    now_unix: u64,
) -> Result<(), AttestationError> {
    if fmt != "apple" {
        return Err(AttestationError::WrongFormat {
            got: fmt.to_string(),
        });
    }
    if x5c.is_empty() {
        return Err(AttestationError::NoChain);
    }
    if x5c.len() > MAX_CHAIN {
        return Err(AttestationError::ChainTooLong { got: x5c.len() });
    }

    let chain: Vec<Certificate> = x5c
        .iter()
        .enumerate()
        .map(|(index, der)| {
            Certificate::from_der(der).map_err(|_| AttestationError::MalformedCertificate { index })
        })
        .collect::<Result<_, _>>()?;

    let root = Certificate::from_pem(APPLE_ROOT_PEM).map_err(|_| AttestationError::BadAnchor)?;

    // 2. Validity, every certificate including the anchor. An expired
    //    anchor must fail closed rather than quietly stop being checked.
    for (index, cert) in chain.iter().chain(std::iter::once(&root)).enumerate() {
        if !is_valid_at(cert, now_unix) {
            return Err(AttestationError::CertificateExpired { index });
        }
    }

    // 3. Each certificate signed by the next; the last signed by the
    //    pinned root. Note the root is NOT taken from the chain — a
    //    self-signed certificate the sender supplies and the sender
    //    verifies is not a trust anchor, it is a formality, and that is
    //    the classic way a chain check gets built wrong.
    for index in 0..chain.len() {
        let issuer = chain.get(index + 1).unwrap_or(&root);
        verify_signed_by(&chain[index], issuer, index)?;
    }
    // The top of the supplied chain must actually be Apple's, which the
    // signature above establishes cryptographically. Re-asserted here as
    // a named error so a failure reads as "untrusted chain" rather than
    // "bad signature at link N".
    if !is_signed_by(chain.last().expect("non-empty"), &root) {
        return Err(AttestationError::UntrustedChain);
    }

    let leaf = &chain[0];

    // 4. The nonce ties this chain to THIS ceremony.
    let mut hasher = Sha256::new();
    hasher.update(auth_data);
    hasher.update(Sha256::digest(client_data_json));
    let expected_nonce = hasher.finalize();

    let nonce = apple_nonce(leaf).ok_or(AttestationError::NoNonce)?;
    if nonce.as_slice() != expected_nonce.as_slice() {
        return Err(AttestationError::NonceMismatch);
    }

    // 5. …and to THIS credential.
    let leaf_key = leaf
        .tbs_certificate
        .subject_public_key_info
        .subject_public_key
        .as_bytes()
        .ok_or(AttestationError::KeyMismatch)?;
    let mut want = Vec::with_capacity(65);
    want.push(0x04);
    want.extend_from_slice(&credential_key.x);
    want.extend_from_slice(&credential_key.y);
    if leaf_key != want.as_slice() {
        return Err(AttestationError::KeyMismatch);
    }

    Ok(())
}

fn is_valid_at(cert: &Certificate, now_unix: u64) -> bool {
    let v = &cert.tbs_certificate.validity;
    let not_before = v.not_before.to_unix_duration().as_secs();
    let not_after = v.not_after.to_unix_duration().as_secs();
    now_unix >= not_before && now_unix <= not_after
}

fn verify_signed_by(
    subject: &Certificate,
    issuer: &Certificate,
    index: usize,
) -> Result<(), AttestationError> {
    let tbs = subject
        .tbs_certificate
        .to_der()
        .map_err(|_| AttestationError::MalformedCertificate { index })?;
    let sig = subject
        .signature
        .as_bytes()
        .ok_or(AttestationError::BadSignature { index })?;

    let digest: Vec<u8> = match subject.signature_algorithm.oid {
        ECDSA_SHA256 => Sha256::digest(&tbs).to_vec(),
        ECDSA_SHA384 => Sha384::digest(&tbs).to_vec(),
        oid => {
            return Err(AttestationError::UnsupportedSignatureAlgorithm {
                oid: oid.to_string(),
            })
        }
    };

    let spki = &issuer.tbs_certificate.subject_public_key_info;
    let curve: ObjectIdentifier = spki
        .algorithm
        .parameters
        .as_ref()
        .and_then(|p| p.decode_as().ok())
        .ok_or(AttestationError::UnsupportedCurve)?;
    let point = spki
        .subject_public_key
        .as_bytes()
        .ok_or(AttestationError::UnsupportedCurve)?;

    // `verify_prehash` rather than a `DigestVerifier`: the digest and
    // the curve are chosen independently by the certificate, so
    // P-384-signs-with-SHA-256 is a real combination the type-level
    // digest binding cannot express.
    let ok = match curve {
        P256_CURVE => {
            use p256::ecdsa::signature::hazmat::PrehashVerifier as _;
            p256::ecdsa::VerifyingKey::from_sec1_bytes(point).is_ok_and(|k| {
                p256::ecdsa::Signature::from_der(sig)
                    .is_ok_and(|s| k.verify_prehash(&digest, &s).is_ok())
            })
        }
        P384_CURVE => {
            use p384::ecdsa::signature::hazmat::PrehashVerifier as _;
            p384::ecdsa::VerifyingKey::from_sec1_bytes(point).is_ok_and(|k| {
                p384::ecdsa::Signature::from_der(sig)
                    .is_ok_and(|s| k.verify_prehash(&digest, &s).is_ok())
            })
        }
        _ => return Err(AttestationError::UnsupportedCurve),
    };

    if ok {
        Ok(())
    } else {
        Err(AttestationError::BadSignature { index })
    }
}

fn is_signed_by(subject: &Certificate, issuer: &Certificate) -> bool {
    verify_signed_by(subject, issuer, 0).is_ok()
}

/// Pull the 32-byte nonce out of Apple's extension.
///
/// The extension value is `SEQUENCE { [1] { OCTET STRING nonce } }`.
/// Walked by hand rather than through a derived type because it is
/// three nested headers and a fixed length, and a hand walk that
/// refuses everything unexpected is easier to audit than a decoder that
/// accepts a family of shapes.
fn apple_nonce(leaf: &Certificate) -> Option<Vec<u8>> {
    let ext = leaf
        .tbs_certificate
        .extensions
        .as_ref()?
        .iter()
        .find(|e| e.extn_id == APPLE_NONCE_EXT)?;
    let raw = ext.extn_value.as_bytes();

    // SEQUENCE
    let rest = strip(raw, 0x30)?;
    // [1] constructed
    let rest = strip(rest, 0xA1)?;
    // OCTET STRING
    let nonce = strip(rest, 0x04)?;
    (nonce.len() == 32).then(|| nonce.to_vec())
}

/// Strip one DER header of the expected tag and return its contents.
///
/// Short and long form lengths only, bounded to two length bytes: the
/// structures here are tens of bytes, and accepting a five-byte length
/// would be accepting shapes Apple never sends.
fn strip(raw: &[u8], tag: u8) -> Option<&[u8]> {
    let (&first, rest) = raw.split_first()?;
    if first != tag {
        return None;
    }
    let (&len_byte, rest) = rest.split_first()?;
    let (len, rest) = if len_byte < 0x80 {
        (len_byte as usize, rest)
    } else if len_byte == 0x81 {
        let (&l, rest) = rest.split_first()?;
        (l as usize, rest)
    } else if len_byte == 0x82 {
        let (a, rest) = rest.split_first()?;
        let (b, rest) = rest.split_first()?;
        (((*a as usize) << 8) | *b as usize, rest)
    } else {
        return None;
    };
    rest.get(..len)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root_der() -> Vec<u8> {
        Certificate::from_pem(APPLE_ROOT_PEM)
            .expect("the vendored anchor parses")
            .to_der()
            .expect("re-encodes")
    }

    #[test]
    fn the_vendored_anchor_is_the_certificate_we_reviewed() {
        // A substituted anchor is the single highest-value change an
        // attacker could make to this repository, and it would
        // otherwise be invisible in review — one opaque base64 blob
        // looks like any other.
        let got = hex::encode(Sha256::digest(root_der()));
        assert_eq!(got, APPLE_ROOT_SHA256);
    }

    #[test]
    fn the_anchor_is_self_signed_and_still_inside_its_validity_window() {
        let root = Certificate::from_pem(APPLE_ROOT_PEM).expect("parses");
        assert!(is_signed_by(&root, &root), "the anchor is self-signed");
        // 2026-08-21. Comfortably inside 2020-03-18 .. 2045-03-15.
        assert!(is_valid_at(&root, 1_787_346_526));
        // …and it fails closed once it expires, rather than being
        // silently exempt from the check every other certificate gets.
        assert!(!is_valid_at(&root, 3_000_000_000));
    }

    /// A credential a piece of software generated: a real P-256 key,
    /// and nothing else. This is exactly what a compromised relay could
    /// produce, and the whole point is that it is refused.
    fn software_credential() -> Es256PublicKey {
        let signing = p256::ecdsa::SigningKey::from_bytes(&[7u8; 32].into()).expect("key");
        let point = signing.verifying_key().to_encoded_point(false);
        let mut x = [0u8; 32];
        let mut y = [0u8; 32];
        x.copy_from_slice(point.x().expect("x"));
        y.copy_from_slice(point.y().expect("y"));
        Es256PublicKey { x, y }
    }

    #[test]
    fn a_credential_with_no_attestation_at_all_is_refused() {
        // `fmt: "none"` is what every software authenticator — and the
        // repo's own `VirtualAuthenticator` — produces.
        let err = verify_apple(
            "none",
            &[vec![0x30, 0x00]],
            b"authdata",
            b"{}",
            &software_credential(),
            1_787_346_526,
        )
        .expect_err("a software credential must be refused");
        assert_eq!(
            err,
            AttestationError::WrongFormat {
                got: "none".to_string()
            }
        );
    }

    #[test]
    fn every_other_forged_shape_is_refused_too() {
        let key = software_credential();
        let now = 1_787_346_526;
        // Claiming the right format without a chain.
        assert_eq!(
            verify_apple("apple", &[], b"a", b"{}", &key, now),
            Err(AttestationError::NoChain)
        );
        // A chain of garbage.
        assert!(matches!(
            verify_apple("apple", &[vec![0xff; 64]], b"a", b"{}", &key, now),
            Err(AttestationError::MalformedCertificate { .. })
        ));
        // An absurdly long chain, to make the agent do signature work.
        assert_eq!(
            verify_apple("apple", &vec![vec![0x30, 0x00]; 9], b"a", b"{}", &key, now),
            Err(AttestationError::ChainTooLong { got: 9 })
        );
        // The Apple root, presented as if it were the credential
        // certificate. It IS signed by the anchor (it is the anchor),
        // so this is the sharpest self-signed-chain test available
        // without a real Apple statement — and it must still fail,
        // because it attests no nonce and no credential key.
        assert!(matches!(
            verify_apple("apple", &[root_der()], b"a", b"{}", &key, now),
            Err(AttestationError::NoNonce)
        ));
    }

    #[test]
    fn a_chain_that_does_not_reach_apple_is_refused() {
        // A self-signed certificate the caller generated. The classic
        // way this check gets built wrong is to take the top of the
        // supplied chain as the anchor, which would make this pass.
        let der = self_signed_p256();
        let err = verify_apple(
            "apple",
            &[der],
            b"a",
            b"{}",
            &software_credential(),
            1_787_346_526,
        )
        .expect_err("an attacker-rooted chain must be refused");
        assert!(
            matches!(
                err,
                AttestationError::BadSignature { .. } | AttestationError::UntrustedChain
            ),
            "unexpected: {err}"
        );
    }

    /// A self-signed P-256 certificate, built the way an attacker would.
    fn self_signed_p256() -> Vec<u8> {
        let mut params =
            rcgen::CertificateParams::new(vec!["attacker.invalid".to_string()]).expect("params");
        params.is_ca = rcgen::IsCa::NoCa;
        let key = rcgen::KeyPair::generate_for(&rcgen::PKCS_ECDSA_P256_SHA256).expect("key");
        params.self_signed(&key).expect("sign").der().to_vec()
    }

    #[test]
    fn the_der_walk_refuses_shapes_apple_never_sends() {
        assert_eq!(
            strip(&[0x30, 0x02, 0xAA, 0xBB], 0x30),
            Some(&[0xAA, 0xBB][..])
        );
        assert_eq!(strip(&[0x30, 0x02, 0xAA, 0xBB], 0x04), None, "wrong tag");
        assert_eq!(strip(&[0x30, 0x05, 0xAA], 0x30), None, "truncated");
        assert_eq!(strip(&[], 0x30), None);
        // A five-byte length is a shape this hierarchy never uses.
        assert_eq!(strip(&[0x30, 0x84, 0, 0, 0, 1, 0xAA], 0x30), None);
    }

    #[test]
    fn an_unsupported_curve_or_algorithm_fails_closed() {
        // Neither is silently treated as "verified".
        let e = AttestationError::UnsupportedSignatureAlgorithm {
            oid: "1.2.3".into(),
        };
        assert!(e.to_string().contains("unsupported signature algorithm"));
        assert!(AttestationError::UnsupportedCurve
            .to_string()
            .contains("unsupported public key curve"));
    }
}
