"""Shared pytest fixtures.

**ADR-0112 Part A.** The synthetic-STL fixtures (`_cube_mesh`,
`_plate_mesh`, `cube_stl_path`, `thin_plate_stl_path`,
`long_thin_concave_proxy_path`) are gone along with the STL parser and
the `numpy-stl` dependency they were built on. Everything now runs off
the committed STEP fixtures below.

STEP fixtures are committed binaries under `tests/fixtures/` — OCCT
writes files that don't round-trip byte-identically if regenerated by a
different OCCT minor, so we pin a generated-once copy rather than
re-writing per test. `tools/generate_step_fixtures.py` is the generator
of record; it is run by hand when a fixture is added, never by the suite.
Tests using these skip if `cadquery-ocp` isn't installed.
"""

from __future__ import annotations

from pathlib import Path

import pytest

_FIXTURES_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture
def step_cube_path() -> Path:
    """20 mm cube STEP, generated once via OCP and committed to the tree."""
    return _FIXTURES_DIR / "unit_cube.step"


@pytest.fixture
def step_thin_plate_path() -> Path:
    """100 × 50 × 0.8 mm plate STEP — trips thin_wall_present, fails 5-axis."""
    return _FIXTURES_DIR / "thin_plate.step"


@pytest.fixture
def step_assembly_path() -> Path:
    """Two-solid STEP — exercises the assembly-rejection error path."""
    return _FIXTURES_DIR / "assembly_two_solids.step"


@pytest.fixture
def fixtures_dir() -> Path:
    """Directory holding every committed STEP fixture."""
    return _FIXTURES_DIR
